BPP_Route_Kalimdor = {
    name = "Kalimdor",
    steps = {
        { text = "Go to Ashenvale", mapID = 63 },
        { text = "Capture Beetle", mapID = 63, speciesID = 406, coord = {18, 39} },
        { text = "Capture Forest Moth", mapID = 63, speciesID = 752, coord = {86, 46} },
        { text = "Capture Rabbit", mapID = 63, speciesID = 378, coord = {28, 21} },
        { text = "Capture Rat", mapID = 63, speciesID = 417, coord = {36, 49} },
        { text = "Capture Roach", mapID = 63, speciesID = 424, coord = {34, 49} },
        { text = "Capture Squirrel", mapID = 63, speciesID = 379, coord = {85, 46} },
        { text = "Capture Toad", mapID = 63, speciesID = 420, coord = {18, 39} },

        { text = "Go to Azshara", mapID = 76 },
        { text = "Capture Rabbit", mapID = 76, speciesID = 378, coord = {59, 29} },
        { text = "Capture Rat", mapID = 76, speciesID = 417, coord = {47, 74} },
        { text = "Capture Roach", mapID = 76, speciesID = 424, coord = {47, 74} },
        { text = "Capture Robo-Chick", mapID = 76, speciesID = 471, coord = {59, 52} },
        { text = "Capture Skunk", mapID = 76, speciesID = 397, coord = {60, 20} },
        { text = "Capture Spider", mapID = 76, speciesID = 404, coord = {42, 76} },
        { text = "Capture Squirrel", mapID = 76, speciesID = 379, coord = {60, 20} },

        { text = "Go to Azuremyst Isle", mapID = 97 },
        { text = "Capture Chicken", mapID = 97, speciesID = 646, coord = {50, 52} },
        { text = "Capture Grey Moth", mapID = 97, speciesID = 464, coord = {44, 26} },
        { text = "Capture Rabbit", mapID = 97, speciesID = 378, coord = {35, 34} },
        { text = "Capture Rat", mapID = 97, speciesID = 417, coord = {48, 41} },
        { text = "Capture Skunk", mapID = 97, speciesID = 397, coord = {35, 34} },
        { text = "Capture Squirrel", mapID = 97, speciesID = 379, coord = {44, 26} },

        { text = "Go to Bloodmyst Isle", mapID = 106 },
        { text = "Capture Chicken", mapID = 106, speciesID = 646, coord = {56, 56} },
        { text = "Capture Infected Fawn", mapID = 106, speciesID = 628, coord = {36, 61} },
        { text = "Capture Infected Squirrel", mapID = 106, speciesID = 627, coord = {33, 40} },
        { text = "Capture Rat", mapID = 106, speciesID = 417, coord = {56, 56} },

        { text = "Go to Darkshore", mapID = 62 },
        { text = "Capture Beetle", mapID = 62, speciesID = 406, coord = {51, 21} },
        { text = "Capture Rabbit", mapID = 62, speciesID = 378, coord = {50, 30} },
        { text = "Capture Rat", mapID = 62, speciesID = 417, coord = {50, 30} },
        { text = "Capture Squirrel", mapID = 62, speciesID = 379, coord = {51, 21} },

        { text = "Go to Desolace", mapID = 66 },
        { text = "Capture Adder", mapID = 66, speciesID = 635, coord = {54, 16} },
        { text = "Capture Amethyst Shale Hatchling", mapID = 66, speciesID = 838, coord = {30, 62} },
        { text = "Capture Desert Spider", mapID = 66, speciesID = 511, coord = {63, 30} },
        { text = "Capture Elfin Rabbit", mapID = 66, speciesID = 479, coord = {51, 22} },
        { text = "Capture Forest Moth", mapID = 66, speciesID = 752, coord = {62, 22} },
        { text = "Capture Horny Toad", mapID = 66, speciesID = 483, coord = {70, 19} },
        { text = "Capture Rat", mapID = 66, speciesID = 417, coord = {51, 22} },
        { text = "Capture Red-Tailed Chipmunk", mapID = 66, speciesID = 456, coord = {36, 88} },
        { text = "Capture Roach", mapID = 66, speciesID = 424, coord = {51, 22} },
        { text = "Capture Rock Viper", mapID = 66, speciesID = 482, coord = {78, 23} },
        { text = "Capture Small Frog", mapID = 66, speciesID = 419, coord = {29, 63} },
        { text = "Capture Stone Armadillo", mapID = 66, speciesID = 485, coord = {65, 25} },
        { text = "Capture Topaz Shale Hatchling", mapID = 66, speciesID = 837, coord = {29, 63} },

        { text = "Go to Durotar", mapID = 1 },
        { text = "Capture Adder", mapID = 1, speciesID = 635, coord = {52, 28} },
        { text = "Capture Cockroach", mapID = 1, speciesID = 453, coord = {52, 28} },
        { text = "Capture Creepy Crawly", mapID = 1, speciesID = 468, coord = {44, 34} },
        { text = "Capture Dung Beetle", mapID = 1, speciesID = 467, coord = {53, 20} },
        { text = "Capture Hare", mapID = 1, speciesID = 448, coord = {54, 62} },
        { text = "Capture Spiny Lizard", mapID = 1, speciesID = 635, coord = {44, 34} },
        { text = "Capture Toad", mapID = 1, speciesID = 420, coord = {53, 42} },
        { text = "Capture Water Snake", mapID = 1, speciesID = 418, coord = {38, 47} },

        { text = "Go to Dustwallow Marsh", mapID = 70 },
        { text = "Capture Black Rat", mapID = 70, speciesID = 398, coord = {36, 31} },
        { text = "Capture Mouse", mapID = 70, speciesID = 385, coord = {36, 31} },
        { text = "Capture Snake", mapID = 70, speciesID = 387, coord = {36, 31} },
        { text = "Capture Spawn of Onyxia", mapID = 70, speciesID = 423, coord = {48, 75} },
        { text = "Capture Spider", mapID = 70, speciesID = 404, coord = {36, 31} },
        { text = "Capture Toad", mapID = 70, speciesID = 420, coord = {55, 26} },

        { text = "Go to Felwood", mapID = 77 },
        { text = "Capture Beetle", mapID = 77, speciesID = 406, coord = {41, 46} },
        { text = "Capture Minfernal", mapID = 77, speciesID = 500, coord = {42, 45} },
        { text = "Capture Rabbit", mapID = 77, speciesID = 378, coord = {41, 46} },
        { text = "Capture Tainted Cockroach", mapID = 77, speciesID = 439, coord = {40, 56} },
        { text = "Capture Tainted Moth", mapID = 77, speciesID = 438, coord = {40, 56} },
        { text = "Capture Tainted Rat", mapID = 77, speciesID = 437, coord = {40, 56} },
        { text = "Capture Toad", mapID = 77, speciesID = 420, coord = {41, 46} },

        { text = "Go to Feralas", mapID = 69 },
        { text = "Capture Nether Faerie Dragon", mapID = 69, speciesID = 756, coord = {66, 43} },
        { text = "Capture Rabbit", mapID = 69, speciesID = 378, coord = {51, 24} },
        { text = "Capture Snake", mapID = 69, speciesID = 387, coord = {51, 24} },
        { text = "Capture Stunted Yeti", mapID = 69, speciesID = 1143, coord = {53, 55} },
        { text = "Capture Squirrel", mapID = 69, speciesID = 379, coord = {51, 24} },

        { text = "Go to Moonglade", mapID = 80 },
        { text = "Capture Forest Moth", mapID = 80, speciesID = 752, coord = {52, 36} },
        { text = "Capture Rabbit", mapID = 80, speciesID = 378, coord = {52, 36} },
        { text = "Capture Silky Moth", mapID = 80, speciesID = 568, coord = {52, 36} },
        { text = "Capture Squirrel", mapID = 80, speciesID = 379, coord = {52, 36} },

        { text = "Go to Mulgore", mapID = 7 },
        { text = "Capture Gazelle Fawn", mapID = 7, speciesID = 477, coord = {44, 62} },
        { text = "Capture Mouse", mapID = 7, speciesID = 385, coord = {48, 53} },
        { text = "Capture Prairie Dog", mapID = 7, speciesID = 386, coord = {49, 63} },
        { text = "Capture Rabbit", mapID = 7, speciesID = 378, coord = {48, 53} },

        { text = "Go to Northern Barrens", mapID = 10 },
        { text = "Capture Adder", mapID = 10, speciesID = 635, coord = {39, 52} },
        { text = "Capture Cheetah Cub", mapID = 10, speciesID = 474, coord = {44, 62} },
        { text = "Capture Prairie Dog", mapID = 10, speciesID = 635, coord = {38, 46} },

        { text = "Go to Silithus", mapID = 81 },
        { text = "Capture Beetle", mapID = 81, speciesID = 406, coord = {41, 45} },
        { text = "Capture Desert Spider", mapID = 81, speciesID = 511, coord = {55, 34} },
        { text = "Capture Qiraji Guardling (Summer only)", mapID = 81, speciesID = 1155, coord = {36, 18} },
        { text = "Capture Rock Viper", mapID = 81, speciesID = 482, coord = {45, 38} },
        { text = "Capture Scarab Hatchling", mapID = 81, speciesID = 559, coord = {41, 44} },
        { text = "Capture Scorpid", mapID = 81, speciesID = 414, coord = {51, 41} },
        { text = "Capture Sidewinder", mapID = 81, speciesID = 512, coord = {39, 22} },
        { text = "Capture Spiky Lizard", mapID = 81, speciesID = 635, coord = {60, 17} },

        { text = "Go to Southern Barrens", mapID = 199 },
        { text = "Capture Adder", mapID = 199, speciesID = 635, coord = {46, 54} },
        { text = "Capture Prairie Dog", mapID = 199, speciesID = 635, coord = {42, 50} },
        { text = "Capture Rat", mapID = 199, speciesID = 417, coord = {39, 39} },
        { text = "Capture Squirrel", mapID = 199, speciesID = 379, coord = {41, 47} },

        { text = "Go to Stonetalon Mountains", mapID = 65 },
        { text = "Capture Beetle", mapID = 65, speciesID = 406, coord = {54, 72} },
        { text = "Capture Chipmunk", mapID = 65, speciesID = 378, coord = {59, 64} },
        { text = "Capture Creepy Crawly", mapID = 65, speciesID = 468, coord = {66, 86} },
        { text = "Capture Forest Moth", mapID = 65, speciesID = 752, coord = {66, 86} },
        { text = "Capture Mouse", mapID = 65, speciesID = 385, coord = {59, 64} },
        { text = "Capture Rabbit", mapID = 65, speciesID = 378, coord = {59, 64} },
        { text = "Capture Squirrel", mapID = 65, speciesID = 379, coord = {59, 64} },

        { text = "Go to Tanaris", mapID = 71 },
        { text = "Capture Beetle", mapID = 71, speciesID = 406, coord = {36, 46} },
        { text = "Capture Desert Spider", mapID = 71, speciesID = 511, coord = {36, 46} },
        { text = "Capture Sand Kitten", mapID = 71, speciesID = 411, coord = {34, 45} },
        { text = "Capture Sidewinder", mapID = 71, speciesID = 512, coord = {44, 37} },
        { text = "Capture Silky Moth", mapID = 71, speciesID = 568, coord = {36, 46} },
        { text = "Capture Small Frog", mapID = 71, speciesID = 419, coord = {36, 46} },
        { text = "Capture Stunted Yeti", mapID = 71, speciesID = 1143, coord = {36, 46} },
        { text = "Capture Tainted Cockroach", mapID = 71, speciesID = 439, coord = {36, 46} },
        { text = "Capture Tainted Moth", mapID = 71, speciesID = 438, coord = {36, 46} },
        { text = "Capture Tainted Rat", mapID = 71, speciesID = 437, coord = {36, 46} },
        { text = "Capture Topaz Shale Hatchling", mapID = 71, speciesID = 837, coord = {44, 37} },

        { text = "Go to Teldrassil", mapID = 57 },
        { text = "Capture Elfin Rabbit", mapID = 57, speciesID = 479, coord = {56, 60} },
        { text = "Capture Forest Moth", mapID = 57, speciesID = 752, coord = {56, 60} },
        { text = "Capture Red-Tailed Chipmunk", mapID = 57, speciesID = 456, coord = {55, 60} },
        { text = "Capture Small Frog", mapID = 57, speciesID = 419, coord = {56, 60} },
        { text = "Capture Squirrel", mapID = 57, speciesID = 379, coord = {56, 60} },

        { text = "Go to Thousand Needles", mapID = 64 },
        { text = "Capture Beetle", mapID = 64, speciesID = 406, coord = {68, 85} },
        { text = "Capture Creepy Crawly", mapID = 64, speciesID = 468, coord = {68, 85} },
        { text = "Capture Forest Moth", mapID = 64, speciesID = 752, coord = {68, 85} },
        { text = "Capture Mouse", mapID = 64, speciesID = 385, coord = {68, 85} },
        { text = "Capture Rabbit", mapID = 64, speciesID = 378, coord = {68, 85} },
        { text = "Capture Squirrel", mapID = 64, speciesID = 379, coord = {68, 85} },

        { text = "Go to Un'Goro Crater", mapID = 78 },
        { text = "Capture Silky Moth", mapID = 78, speciesID = 568, coord = {55, 62} },

        { text = "Go to Winterspring", mapID = 83 },
        { text = "Capture Alpine Chipmunk", mapID = 83, speciesID = 487, coord = {51, 47} },
        { text = "Capture Mountain Skunk", mapID = 83, speciesID = 633, coord = {54, 44} },
        { text = "Capture Rabid Nut Varmint 5000", mapID = 83, speciesID = 1167, coord = {59, 51} },
        { text = "Capture Robo-Chick", mapID = 83, speciesID = 471, coord = {59, 51} },
        { text = "Capture Spider", mapID = 83, speciesID = 404, coord = {51, 47} },

        { text = "Go to Darnassus", mapID = 89 },
        { text = "Capture Elfin Rabbit", mapID = 89, speciesID = 479, coord = {61, 49} },
        { text = "Capture Forest Moth", mapID = 89, speciesID = 752, coord = {61, 49} },
        { text = "Capture Red-Tailed Chipmunk", mapID = 89, speciesID = 456, coord = {61, 49} },
        { text = "Capture Small Frog", mapID = 89, speciesID = 419, coord = {61, 49} },

        { text = "Go to The Exodar", mapID = 103 },
        { text = "Capture Grey Moth", mapID = 103, speciesID = 464, coord = {55, 46} },
        { text = "Capture Mouse", mapID = 103, speciesID = 385, coord = {55, 46} },

        { text = "Go to Mount Hyjal", mapID = 198 },
        { text = "Capture Alpine Chipmunk", mapID = 198, speciesID = 487, coord = {45, 25} },
        { text = "Capture Elfin Rabbit", mapID = 198, speciesID = 479, coord = {45, 25} },
        { text = "Capture Forest Moth", mapID = 198, speciesID = 752, coord = {45, 25} },
        { text = "Capture Rabbit", mapID = 198, speciesID = 378, coord = {45, 25} },
        { text = "Capture Rock Viper", mapID = 198, speciesID = 482, coord = {45, 25} },
        { text = "Capture Squirrel", mapID = 198, speciesID = 379, coord = {45, 25} },

        { text = "Go to Uldum", mapID = 249 },
        { text = "Capture Desert Spider", mapID = 249, speciesID = 511, coord = {54, 34} },
        { text = "Capture Dung Beetle", mapID = 249, speciesID = 467, coord = {54, 34} },
        { text = "Capture Emerald Boa", mapID = 249, speciesID = 632, coord = {54, 34} },
        { text = "Capture Sidewinder", mapID = 249, speciesID = 512, coord = {54, 34} },

        -- Dungeon:
        { text = "Go to Ahn'Qiraj: The Fallen Kingdom (Dungeon)", mapID = 327 },
        { text = "Capture Scarab Hatchling", mapID = 327, speciesID = 559, coord = {44, 10} },
        { text = "Capture Sidewinder", mapID = 327, speciesID = 512, coord = {44, 10} }
    }
}